export interface BlogPost {
  id: string
  academic_year_id: string
  classrom_id?: string
  title: string
  content: string
  author_id: string
  created_at: string
  published_at?: string
  post_media?: BlogPostMedia[]
  post_views?: number
  post_clicks?: number
  users: {
    id: string
    full_name: string
    email: string
  },
  classrooms: {
    id: string
    name: string
  }
}

export type MediaType = "photo" | "video" | "document" | "thumbnail"

export interface BlogPostMedia {
  id: string
  post_id: string
  file_url: string
  media_type: MediaType
  mime_type?: string // e.g., "application/pdf", "video/mp4", "image/jpeg"
  file_size?: number // in bytes
  thumbnail_url?: string // For video thumbnails (generated by backend)
  caption?: string
  author_id: string
  created_at: string
  deleted_at?: string
}

export interface BlogPostViewStats {
  post_id: string,
  user: {
    id: string,
    full_name: string,
    email: string
  },
  count: number,
}